#!/usr/bin/env bash

# Copyright © 2021 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

prog="${0#**/}"
bad_usage()
{
    printf 'Usage: %s ZIP-CODE\n' "$prog" >&2
    exit 1

}
[ $# -eq 1 ] || bad_usage
zip="$1"
case $zip in
    [0-9][0-9]-[0-9][0-9][0-9]) ;;
    *) bad_usage;
esac
user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0'
xcurl() {
    curl \
        --silent --fail --show-error \
        -H "User-Agent: $user_agent" \
        "$@"
}
json=$(
xcurl 'https://inpost.pl/godziny-odbiorow/sprawdz' \
    -H 'Accept: application/json, text/javascript, */*; q=0.01' \
    -H 'X-Requested-With: XMLHttpRequest' \
    --data-raw '{"zipcode":"'"$zip"'"}'
)
zone=$(jq -r .zone <<< "$json")
case $zone in
    A) h=16;;
    B) h=15;;
    C) h=14;;
    D) h=13;;
    '') printf '%s: no zone info for %s\n' "$prog" "$zip" >&2; exit 1;;
    *) printf '%s: unknown zone for %s: %s\n' "$prog" "$zip" "$zone" >&2; exit 1;;
esac
printf '%s:00\n' "$h"

# vim:ts=4 sts=4 sw=4 et
